#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVien")]
	public partial class QuanLyThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_can_bo_thu_vien(tbl_can_bo_thu_vien instance);
    partial void Updatetbl_can_bo_thu_vien(tbl_can_bo_thu_vien instance);
    partial void Deletetbl_can_bo_thu_vien(tbl_can_bo_thu_vien instance);
    partial void Inserttbl_the_loai_sach(tbl_the_loai_sach instance);
    partial void Updatetbl_the_loai_sach(tbl_the_loai_sach instance);
    partial void Deletetbl_the_loai_sach(tbl_the_loai_sach instance);
    partial void Inserttbl_chi_tiet_muon_tra(tbl_chi_tiet_muon_tra instance);
    partial void Updatetbl_chi_tiet_muon_tra(tbl_chi_tiet_muon_tra instance);
    partial void Deletetbl_chi_tiet_muon_tra(tbl_chi_tiet_muon_tra instance);
    partial void Inserttbl_doc_gia(tbl_doc_gia instance);
    partial void Updatetbl_doc_gia(tbl_doc_gia instance);
    partial void Deletetbl_doc_gia(tbl_doc_gia instance);
    partial void Inserttbl_kho_sach(tbl_kho_sach instance);
    partial void Updatetbl_kho_sach(tbl_kho_sach instance);
    partial void Deletetbl_kho_sach(tbl_kho_sach instance);
    partial void Inserttbl_khoa(tbl_khoa instance);
    partial void Updatetbl_khoa(tbl_khoa instance);
    partial void Deletetbl_khoa(tbl_khoa instance);
    partial void Inserttbl_lop(tbl_lop instance);
    partial void Updatetbl_lop(tbl_lop instance);
    partial void Deletetbl_lop(tbl_lop instance);
    partial void Inserttbl_muon_tra(tbl_muon_tra instance);
    partial void Updatetbl_muon_tra(tbl_muon_tra instance);
    partial void Deletetbl_muon_tra(tbl_muon_tra instance);
    partial void Inserttbl_NXB(tbl_NXB instance);
    partial void Updatetbl_NXB(tbl_NXB instance);
    partial void Deletetbl_NXB(tbl_NXB instance);
    partial void Inserttbl_sach(tbl_sach instance);
    partial void Updatetbl_sach(tbl_sach instance);
    partial void Deletetbl_sach(tbl_sach instance);
    #endregion
		
		public QuanLyThuVienDataContext() : 
				base(global::Model.Properties.Settings.Default.QuanLyThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_can_bo_thu_vien> tbl_can_bo_thu_viens
		{
			get
			{
				return this.GetTable<tbl_can_bo_thu_vien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_the_loai_sach> tbl_the_loai_saches
		{
			get
			{
				return this.GetTable<tbl_the_loai_sach>();
			}
		}
		
		public System.Data.Linq.Table<tbl_chi_tiet_muon_tra> tbl_chi_tiet_muon_tras
		{
			get
			{
				return this.GetTable<tbl_chi_tiet_muon_tra>();
			}
		}
		
		public System.Data.Linq.Table<tbl_doc_gia> tbl_doc_gias
		{
			get
			{
				return this.GetTable<tbl_doc_gia>();
			}
		}
		
		public System.Data.Linq.Table<tbl_kho_sach> tbl_kho_saches
		{
			get
			{
				return this.GetTable<tbl_kho_sach>();
			}
		}
		
		public System.Data.Linq.Table<tbl_khoa> tbl_khoas
		{
			get
			{
				return this.GetTable<tbl_khoa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lop> tbl_lops
		{
			get
			{
				return this.GetTable<tbl_lop>();
			}
		}
		
		public System.Data.Linq.Table<tbl_muon_tra> tbl_muon_tras
		{
			get
			{
				return this.GetTable<tbl_muon_tra>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NXB> tbl_NXBs
		{
			get
			{
				return this.GetTable<tbl_NXB>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sach> tbl_saches
		{
			get
			{
				return this.GetTable<tbl_sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_can_bo_thu_vien")]
	public partial class tbl_can_bo_thu_vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCanBo;
		
		private string _tenCanBo;
		
		private string _gioiTinh;
		
		private System.Nullable<System.DateTime> _namSinh;
		
		private string _diaChi;
		
		private string _phone;
		
		private string _email;
		
		private string _quenHan;
		
		private string _matKhau;
		
		private EntitySet<tbl_chi_tiet_muon_tra> _tbl_chi_tiet_muon_tras;
		
		private EntitySet<tbl_chi_tiet_muon_tra> _tbl_chi_tiet_muon_tras1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCanBoChanging(int value);
    partial void OnmaCanBoChanged();
    partial void OntenCanBoChanging(string value);
    partial void OntenCanBoChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnnamSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnnamSinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnquenHanChanging(string value);
    partial void OnquenHanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public tbl_can_bo_thu_vien()
		{
			this._tbl_chi_tiet_muon_tras = new EntitySet<tbl_chi_tiet_muon_tra>(new Action<tbl_chi_tiet_muon_tra>(this.attach_tbl_chi_tiet_muon_tras), new Action<tbl_chi_tiet_muon_tra>(this.detach_tbl_chi_tiet_muon_tras));
			this._tbl_chi_tiet_muon_tras1 = new EntitySet<tbl_chi_tiet_muon_tra>(new Action<tbl_chi_tiet_muon_tra>(this.attach_tbl_chi_tiet_muon_tras1), new Action<tbl_chi_tiet_muon_tra>(this.detach_tbl_chi_tiet_muon_tras1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCanBo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCanBo
		{
			get
			{
				return this._maCanBo;
			}
			set
			{
				if ((this._maCanBo != value))
				{
					this.OnmaCanBoChanging(value);
					this.SendPropertyChanging();
					this._maCanBo = value;
					this.SendPropertyChanged("maCanBo");
					this.OnmaCanBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCanBo", DbType="NVarChar(50)")]
		public string tenCanBo
		{
			get
			{
				return this._tenCanBo;
			}
			set
			{
				if ((this._tenCanBo != value))
				{
					this.OntenCanBoChanging(value);
					this.SendPropertyChanging();
					this._tenCanBo = value;
					this.SendPropertyChanged("tenCanBo");
					this.OntenCanBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(5)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namSinh", DbType="Date")]
		public System.Nullable<System.DateTime> namSinh
		{
			get
			{
				return this._namSinh;
			}
			set
			{
				if ((this._namSinh != value))
				{
					this.OnnamSinhChanging(value);
					this.SendPropertyChanging();
					this._namSinh = value;
					this.SendPropertyChanged("namSinh");
					this.OnnamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(200)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quenHan", DbType="VarChar(20)")]
		public string quenHan
		{
			get
			{
				return this._quenHan;
			}
			set
			{
				if ((this._quenHan != value))
				{
					this.OnquenHanChanging(value);
					this.SendPropertyChanging();
					this._quenHan = value;
					this.SendPropertyChanged("quenHan");
					this.OnquenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_can_bo_thu_vien_tbl_chi_tiet_muon_tra", Storage="_tbl_chi_tiet_muon_tras", ThisKey="maCanBo", OtherKey="maCanBoMuon")]
		public EntitySet<tbl_chi_tiet_muon_tra> tbl_chi_tiet_muon_tras
		{
			get
			{
				return this._tbl_chi_tiet_muon_tras;
			}
			set
			{
				this._tbl_chi_tiet_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_can_bo_thu_vien_tbl_chi_tiet_muon_tra1", Storage="_tbl_chi_tiet_muon_tras1", ThisKey="maCanBo", OtherKey="maCanBoTra")]
		public EntitySet<tbl_chi_tiet_muon_tra> tbl_chi_tiet_muon_tras1
		{
			get
			{
				return this._tbl_chi_tiet_muon_tras1;
			}
			set
			{
				this._tbl_chi_tiet_muon_tras1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_can_bo_thu_vien = this;
		}
		
		private void detach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_can_bo_thu_vien = null;
		}
		
		private void attach_tbl_chi_tiet_muon_tras1(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_can_bo_thu_vien1 = this;
		}
		
		private void detach_tbl_chi_tiet_muon_tras1(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_can_bo_thu_vien1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_the_loai_sach")]
	public partial class tbl_the_loai_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTheLoai;
		
		private string _tenTheLoai;
		
		private string _ghiChu;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTheLoaiChanging(int value);
    partial void OnmaTheLoaiChanged();
    partial void OntenTheLoaiChanging(string value);
    partial void OntenTheLoaiChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public tbl_the_loai_sach()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTheLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTheLoai
		{
			get
			{
				return this._maTheLoai;
			}
			set
			{
				if ((this._maTheLoai != value))
				{
					this.OnmaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._maTheLoai = value;
					this.SendPropertyChanged("maTheLoai");
					this.OnmaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTheLoai", DbType="NVarChar(50)")]
		public string tenTheLoai
		{
			get
			{
				return this._tenTheLoai;
			}
			set
			{
				if ((this._tenTheLoai != value))
				{
					this.OntenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenTheLoai = value;
					this.SendPropertyChanged("tenTheLoai");
					this.OntenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_the_loai_sach_tbl_sach", Storage="_tbl_saches", ThisKey="maTheLoai", OtherKey="maTheLoai")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_the_loai_sach = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_the_loai_sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_chi_tiet_muon_tra")]
	public partial class tbl_chi_tiet_muon_tra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _muon_tra_id;
		
		private int _maSach;
		
		private System.Nullable<int> _maCanBoMuon;
		
		private System.Nullable<int> _maCanBoTra;
		
		private System.Nullable<System.DateTime> _ngayMuon;
		
		private System.Nullable<System.DateTime> _ngayPhaiTra;
		
		private string _tinhTrangMuon;
		
		private System.Nullable<System.DateTime> _ngayTra;
		
		private string _tinhTrangTra;
		
		private System.Nullable<double> _thanhToan;
		
		private string _ghiChu;
		
		private EntityRef<tbl_can_bo_thu_vien> _tbl_can_bo_thu_vien;
		
		private EntityRef<tbl_can_bo_thu_vien> _tbl_can_bo_thu_vien1;
		
		private EntityRef<tbl_muon_tra> _tbl_muon_tra;
		
		private EntityRef<tbl_sach> _tbl_sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmuon_tra_idChanging(int value);
    partial void Onmuon_tra_idChanged();
    partial void OnmaSachChanging(int value);
    partial void OnmaSachChanged();
    partial void OnmaCanBoMuonChanging(System.Nullable<int> value);
    partial void OnmaCanBoMuonChanged();
    partial void OnmaCanBoTraChanging(System.Nullable<int> value);
    partial void OnmaCanBoTraChanged();
    partial void OnngayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngayMuonChanged();
    partial void OnngayPhaiTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayPhaiTraChanged();
    partial void OntinhTrangMuonChanging(string value);
    partial void OntinhTrangMuonChanged();
    partial void OnngayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTraChanged();
    partial void OntinhTrangTraChanging(string value);
    partial void OntinhTrangTraChanged();
    partial void OnthanhToanChanging(System.Nullable<double> value);
    partial void OnthanhToanChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public tbl_chi_tiet_muon_tra()
		{
			this._tbl_can_bo_thu_vien = default(EntityRef<tbl_can_bo_thu_vien>);
			this._tbl_can_bo_thu_vien1 = default(EntityRef<tbl_can_bo_thu_vien>);
			this._tbl_muon_tra = default(EntityRef<tbl_muon_tra>);
			this._tbl_sach = default(EntityRef<tbl_sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_muon_tra_id", DbType="Int NOT NULL")]
		public int muon_tra_id
		{
			get
			{
				return this._muon_tra_id;
			}
			set
			{
				if ((this._muon_tra_id != value))
				{
					this.Onmuon_tra_idChanging(value);
					this.SendPropertyChanging();
					this._muon_tra_id = value;
					this.SendPropertyChanged("muon_tra_id");
					this.Onmuon_tra_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int NOT NULL")]
		public int maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					if (this._tbl_sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCanBoMuon", DbType="Int")]
		public System.Nullable<int> maCanBoMuon
		{
			get
			{
				return this._maCanBoMuon;
			}
			set
			{
				if ((this._maCanBoMuon != value))
				{
					if ((this._tbl_can_bo_thu_vien.HasLoadedOrAssignedValue || this._tbl_muon_tra.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCanBoMuonChanging(value);
					this.SendPropertyChanging();
					this._maCanBoMuon = value;
					this.SendPropertyChanged("maCanBoMuon");
					this.OnmaCanBoMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCanBoTra", DbType="Int")]
		public System.Nullable<int> maCanBoTra
		{
			get
			{
				return this._maCanBoTra;
			}
			set
			{
				if ((this._maCanBoTra != value))
				{
					if (this._tbl_can_bo_thu_vien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCanBoTraChanging(value);
					this.SendPropertyChanging();
					this._maCanBoTra = value;
					this.SendPropertyChanged("maCanBoTra");
					this.OnmaCanBoTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayMuon", DbType="Date")]
		public System.Nullable<System.DateTime> ngayMuon
		{
			get
			{
				return this._ngayMuon;
			}
			set
			{
				if ((this._ngayMuon != value))
				{
					this.OnngayMuonChanging(value);
					this.SendPropertyChanging();
					this._ngayMuon = value;
					this.SendPropertyChanged("ngayMuon");
					this.OnngayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayPhaiTra", DbType="Date")]
		public System.Nullable<System.DateTime> ngayPhaiTra
		{
			get
			{
				return this._ngayPhaiTra;
			}
			set
			{
				if ((this._ngayPhaiTra != value))
				{
					this.OnngayPhaiTraChanging(value);
					this.SendPropertyChanging();
					this._ngayPhaiTra = value;
					this.SendPropertyChanged("ngayPhaiTra");
					this.OnngayPhaiTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangMuon", DbType="NVarChar(100)")]
		public string tinhTrangMuon
		{
			get
			{
				return this._tinhTrangMuon;
			}
			set
			{
				if ((this._tinhTrangMuon != value))
				{
					this.OntinhTrangMuonChanging(value);
					this.SendPropertyChanging();
					this._tinhTrangMuon = value;
					this.SendPropertyChanged("tinhTrangMuon");
					this.OntinhTrangMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTra", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTra
		{
			get
			{
				return this._ngayTra;
			}
			set
			{
				if ((this._ngayTra != value))
				{
					this.OnngayTraChanging(value);
					this.SendPropertyChanging();
					this._ngayTra = value;
					this.SendPropertyChanged("ngayTra");
					this.OnngayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangTra", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tinhTrangTra
		{
			get
			{
				return this._tinhTrangTra;
			}
			set
			{
				if ((this._tinhTrangTra != value))
				{
					this.OntinhTrangTraChanging(value);
					this.SendPropertyChanging();
					this._tinhTrangTra = value;
					this.SendPropertyChanged("tinhTrangTra");
					this.OntinhTrangTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhToan", DbType="Float")]
		public System.Nullable<double> thanhToan
		{
			get
			{
				return this._thanhToan;
			}
			set
			{
				if ((this._thanhToan != value))
				{
					this.OnthanhToanChanging(value);
					this.SendPropertyChanging();
					this._thanhToan = value;
					this.SendPropertyChanged("thanhToan");
					this.OnthanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(100)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_can_bo_thu_vien_tbl_chi_tiet_muon_tra", Storage="_tbl_can_bo_thu_vien", ThisKey="maCanBoMuon", OtherKey="maCanBo", IsForeignKey=true)]
		public tbl_can_bo_thu_vien tbl_can_bo_thu_vien
		{
			get
			{
				return this._tbl_can_bo_thu_vien.Entity;
			}
			set
			{
				tbl_can_bo_thu_vien previousValue = this._tbl_can_bo_thu_vien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_can_bo_thu_vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_can_bo_thu_vien.Entity = null;
						previousValue.tbl_chi_tiet_muon_tras.Remove(this);
					}
					this._tbl_can_bo_thu_vien.Entity = value;
					if ((value != null))
					{
						value.tbl_chi_tiet_muon_tras.Add(this);
						this._maCanBoMuon = value.maCanBo;
					}
					else
					{
						this._maCanBoMuon = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_can_bo_thu_vien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_can_bo_thu_vien_tbl_chi_tiet_muon_tra1", Storage="_tbl_can_bo_thu_vien1", ThisKey="maCanBoTra", OtherKey="maCanBo", IsForeignKey=true)]
		public tbl_can_bo_thu_vien tbl_can_bo_thu_vien1
		{
			get
			{
				return this._tbl_can_bo_thu_vien1.Entity;
			}
			set
			{
				tbl_can_bo_thu_vien previousValue = this._tbl_can_bo_thu_vien1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_can_bo_thu_vien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_can_bo_thu_vien1.Entity = null;
						previousValue.tbl_chi_tiet_muon_tras1.Remove(this);
					}
					this._tbl_can_bo_thu_vien1.Entity = value;
					if ((value != null))
					{
						value.tbl_chi_tiet_muon_tras1.Add(this);
						this._maCanBoTra = value.maCanBo;
					}
					else
					{
						this._maCanBoTra = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_can_bo_thu_vien1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_muon_tra_tbl_chi_tiet_muon_tra", Storage="_tbl_muon_tra", ThisKey="maCanBoMuon", OtherKey="ID", IsForeignKey=true)]
		public tbl_muon_tra tbl_muon_tra
		{
			get
			{
				return this._tbl_muon_tra.Entity;
			}
			set
			{
				tbl_muon_tra previousValue = this._tbl_muon_tra.Entity;
				if (((previousValue != value) 
							|| (this._tbl_muon_tra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_muon_tra.Entity = null;
						previousValue.tbl_chi_tiet_muon_tras.Remove(this);
					}
					this._tbl_muon_tra.Entity = value;
					if ((value != null))
					{
						value.tbl_chi_tiet_muon_tras.Add(this);
						this._maCanBoMuon = value.ID;
					}
					else
					{
						this._maCanBoMuon = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_muon_tra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sach_tbl_chi_tiet_muon_tra", Storage="_tbl_sach", ThisKey="maSach", OtherKey="maSach", IsForeignKey=true)]
		public tbl_sach tbl_sach
		{
			get
			{
				return this._tbl_sach.Entity;
			}
			set
			{
				tbl_sach previousValue = this._tbl_sach.Entity;
				if (((previousValue != value) 
							|| (this._tbl_sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_sach.Entity = null;
						previousValue.tbl_chi_tiet_muon_tras.Remove(this);
					}
					this._tbl_sach.Entity = value;
					if ((value != null))
					{
						value.tbl_chi_tiet_muon_tras.Add(this);
						this._maSach = value.maSach;
					}
					else
					{
						this._maSach = default(int);
					}
					this.SendPropertyChanged("tbl_sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_doc_gia")]
	public partial class tbl_doc_gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maThe;
		
		private System.Nullable<int> _maKhoa;
		
		private System.Nullable<int> _maLop;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _phone;
		
		private string _email;
		
		private EntitySet<tbl_muon_tra> _tbl_muon_tras;
		
		private EntityRef<tbl_khoa> _tbl_khoa;
		
		private EntityRef<tbl_lop> _tbl_lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTheChanging(int value);
    partial void OnmaTheChanged();
    partial void OnmaKhoaChanging(System.Nullable<int> value);
    partial void OnmaKhoaChanged();
    partial void OnmaLopChanging(System.Nullable<int> value);
    partial void OnmaLopChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tbl_doc_gia()
		{
			this._tbl_muon_tras = new EntitySet<tbl_muon_tra>(new Action<tbl_muon_tra>(this.attach_tbl_muon_tras), new Action<tbl_muon_tra>(this.detach_tbl_muon_tras));
			this._tbl_khoa = default(EntityRef<tbl_khoa>);
			this._tbl_lop = default(EntityRef<tbl_lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maThe
		{
			get
			{
				return this._maThe;
			}
			set
			{
				if ((this._maThe != value))
				{
					this.OnmaTheChanging(value);
					this.SendPropertyChanging();
					this._maThe = value;
					this.SendPropertyChanged("maThe");
					this.OnmaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="Int")]
		public System.Nullable<int> maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._tbl_khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="Int")]
		public System.Nullable<int> maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					if (this._tbl_lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NChar(10)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(5)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(200)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_doc_gia_tbl_muon_tra", Storage="_tbl_muon_tras", ThisKey="maThe", OtherKey="maThe")]
		public EntitySet<tbl_muon_tra> tbl_muon_tras
		{
			get
			{
				return this._tbl_muon_tras;
			}
			set
			{
				this._tbl_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_doc_gia", Storage="_tbl_khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public tbl_khoa tbl_khoa
		{
			get
			{
				return this._tbl_khoa.Entity;
			}
			set
			{
				tbl_khoa previousValue = this._tbl_khoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoa.Entity = null;
						previousValue.tbl_doc_gias.Remove(this);
					}
					this._tbl_khoa.Entity = value;
					if ((value != null))
					{
						value.tbl_doc_gias.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_khoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lop_tbl_doc_gia", Storage="_tbl_lop", ThisKey="maLop", OtherKey="maLop", IsForeignKey=true)]
		public tbl_lop tbl_lop
		{
			get
			{
				return this._tbl_lop.Entity;
			}
			set
			{
				tbl_lop previousValue = this._tbl_lop.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lop.Entity = null;
						previousValue.tbl_doc_gias.Remove(this);
					}
					this._tbl_lop.Entity = value;
					if ((value != null))
					{
						value.tbl_doc_gias.Add(this);
						this._maLop = value.maLop;
					}
					else
					{
						this._maLop = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_muon_tras(tbl_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_doc_gia = this;
		}
		
		private void detach_tbl_muon_tras(tbl_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_doc_gia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_kho_sach")]
	public partial class tbl_kho_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKho;
		
		private string _tenKho;
		
		private string _ghiChu;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoChanging(int value);
    partial void OnmaKhoChanged();
    partial void OntenKhoChanging(string value);
    partial void OntenKhoChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public tbl_kho_sach()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKho
		{
			get
			{
				return this._maKho;
			}
			set
			{
				if ((this._maKho != value))
				{
					this.OnmaKhoChanging(value);
					this.SendPropertyChanging();
					this._maKho = value;
					this.SendPropertyChanged("maKho");
					this.OnmaKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKho", DbType="NVarChar(50)")]
		public string tenKho
		{
			get
			{
				return this._tenKho;
			}
			set
			{
				if ((this._tenKho != value))
				{
					this.OntenKhoChanging(value);
					this.SendPropertyChanging();
					this._tenKho = value;
					this.SendPropertyChanged("tenKho");
					this.OntenKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kho_sach_tbl_sach", Storage="_tbl_saches", ThisKey="maKho", OtherKey="maKho")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kho_sach = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kho_sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_khoa")]
	public partial class tbl_khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKhoa;
		
		private string _tenKhoa;
		
		private string _diaChi;
		
		private string _SDT;
		
		private string _email;
		
		private string _truongKhoa;
		
		private EntitySet<tbl_doc_gia> _tbl_doc_gias;
		
		private EntitySet<tbl_lop> _tbl_lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoaChanging(int value);
    partial void OnmaKhoaChanged();
    partial void OntenKhoaChanging(string value);
    partial void OntenKhoaChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntruongKhoaChanging(string value);
    partial void OntruongKhoaChanged();
    #endregion
		
		public tbl_khoa()
		{
			this._tbl_doc_gias = new EntitySet<tbl_doc_gia>(new Action<tbl_doc_gia>(this.attach_tbl_doc_gias), new Action<tbl_doc_gia>(this.detach_tbl_doc_gias));
			this._tbl_lops = new EntitySet<tbl_lop>(new Action<tbl_lop>(this.attach_tbl_lops), new Action<tbl_lop>(this.detach_tbl_lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoa", DbType="NVarChar(50)")]
		public string tenKhoa
		{
			get
			{
				return this._tenKhoa;
			}
			set
			{
				if ((this._tenKhoa != value))
				{
					this.OntenKhoaChanging(value);
					this.SendPropertyChanging();
					this._tenKhoa = value;
					this.SendPropertyChanged("tenKhoa");
					this.OntenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_truongKhoa", DbType="NVarChar(30)")]
		public string truongKhoa
		{
			get
			{
				return this._truongKhoa;
			}
			set
			{
				if ((this._truongKhoa != value))
				{
					this.OntruongKhoaChanging(value);
					this.SendPropertyChanging();
					this._truongKhoa = value;
					this.SendPropertyChanged("truongKhoa");
					this.OntruongKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_doc_gia", Storage="_tbl_doc_gias", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<tbl_doc_gia> tbl_doc_gias
		{
			get
			{
				return this._tbl_doc_gias;
			}
			set
			{
				this._tbl_doc_gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_lop", Storage="_tbl_lops", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<tbl_lop> tbl_lops
		{
			get
			{
				return this._tbl_lops;
			}
			set
			{
				this._tbl_lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_doc_gias(tbl_doc_gia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = this;
		}
		
		private void detach_tbl_doc_gias(tbl_doc_gia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = null;
		}
		
		private void attach_tbl_lops(tbl_lop entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = this;
		}
		
		private void detach_tbl_lops(tbl_lop entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lop")]
	public partial class tbl_lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLop;
		
		private int _maKhoa;
		
		private string _tenLop;
		
		private string _chuNhiem;
		
		private EntitySet<tbl_doc_gia> _tbl_doc_gias;
		
		private EntityRef<tbl_khoa> _tbl_khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLopChanging(int value);
    partial void OnmaLopChanged();
    partial void OnmaKhoaChanging(int value);
    partial void OnmaKhoaChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnchuNhiemChanging(string value);
    partial void OnchuNhiemChanged();
    #endregion
		
		public tbl_lop()
		{
			this._tbl_doc_gias = new EntitySet<tbl_doc_gia>(new Action<tbl_doc_gia>(this.attach_tbl_doc_gias), new Action<tbl_doc_gia>(this.detach_tbl_doc_gias));
			this._tbl_khoa = default(EntityRef<tbl_khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="Int NOT NULL")]
		public int maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._tbl_khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(50)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuNhiem", DbType="NVarChar(50)")]
		public string chuNhiem
		{
			get
			{
				return this._chuNhiem;
			}
			set
			{
				if ((this._chuNhiem != value))
				{
					this.OnchuNhiemChanging(value);
					this.SendPropertyChanging();
					this._chuNhiem = value;
					this.SendPropertyChanged("chuNhiem");
					this.OnchuNhiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lop_tbl_doc_gia", Storage="_tbl_doc_gias", ThisKey="maLop", OtherKey="maLop")]
		public EntitySet<tbl_doc_gia> tbl_doc_gias
		{
			get
			{
				return this._tbl_doc_gias;
			}
			set
			{
				this._tbl_doc_gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_lop", Storage="_tbl_khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public tbl_khoa tbl_khoa
		{
			get
			{
				return this._tbl_khoa.Entity;
			}
			set
			{
				tbl_khoa previousValue = this._tbl_khoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoa.Entity = null;
						previousValue.tbl_lops.Remove(this);
					}
					this._tbl_khoa.Entity = value;
					if ((value != null))
					{
						value.tbl_lops.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(int);
					}
					this.SendPropertyChanged("tbl_khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_doc_gias(tbl_doc_gia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lop = this;
		}
		
		private void detach_tbl_doc_gias(tbl_doc_gia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_muon_tra")]
	public partial class tbl_muon_tra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _maThe;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private EntitySet<tbl_chi_tiet_muon_tra> _tbl_chi_tiet_muon_tras;
		
		private EntityRef<tbl_doc_gia> _tbl_doc_gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmaTheChanging(System.Nullable<int> value);
    partial void OnmaTheChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    #endregion
		
		public tbl_muon_tra()
		{
			this._tbl_chi_tiet_muon_tras = new EntitySet<tbl_chi_tiet_muon_tra>(new Action<tbl_chi_tiet_muon_tra>(this.attach_tbl_chi_tiet_muon_tras), new Action<tbl_chi_tiet_muon_tra>(this.detach_tbl_chi_tiet_muon_tras));
			this._tbl_doc_gia = default(EntityRef<tbl_doc_gia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThe", DbType="Int")]
		public System.Nullable<int> maThe
		{
			get
			{
				return this._maThe;
			}
			set
			{
				if ((this._maThe != value))
				{
					if (this._tbl_doc_gia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTheChanging(value);
					this.SendPropertyChanging();
					this._maThe = value;
					this.SendPropertyChanged("maThe");
					this.OnmaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_muon_tra_tbl_chi_tiet_muon_tra", Storage="_tbl_chi_tiet_muon_tras", ThisKey="ID", OtherKey="maCanBoMuon")]
		public EntitySet<tbl_chi_tiet_muon_tra> tbl_chi_tiet_muon_tras
		{
			get
			{
				return this._tbl_chi_tiet_muon_tras;
			}
			set
			{
				this._tbl_chi_tiet_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_doc_gia_tbl_muon_tra", Storage="_tbl_doc_gia", ThisKey="maThe", OtherKey="maThe", IsForeignKey=true)]
		public tbl_doc_gia tbl_doc_gia
		{
			get
			{
				return this._tbl_doc_gia.Entity;
			}
			set
			{
				tbl_doc_gia previousValue = this._tbl_doc_gia.Entity;
				if (((previousValue != value) 
							|| (this._tbl_doc_gia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_doc_gia.Entity = null;
						previousValue.tbl_muon_tras.Remove(this);
					}
					this._tbl_doc_gia.Entity = value;
					if ((value != null))
					{
						value.tbl_muon_tras.Add(this);
						this._maThe = value.maThe;
					}
					else
					{
						this._maThe = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_doc_gia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_muon_tra = this;
		}
		
		private void detach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_muon_tra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NXB")]
	public partial class tbl_NXB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNXB;
		
		private string _tenNXB;
		
		private string _phone;
		
		private string _email;
		
		private string _diaChi;
		
		private string _ghiChu;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNXBChanging(int value);
    partial void OnmaNXBChanged();
    partial void OntenNXBChanging(string value);
    partial void OntenNXBChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public tbl_NXB()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNXB", DbType="NVarChar(50)")]
		public string tenNXB
		{
			get
			{
				return this._tenNXB;
			}
			set
			{
				if ((this._tenNXB != value))
				{
					this.OntenNXBChanging(value);
					this.SendPropertyChanging();
					this._tenNXB = value;
					this.SendPropertyChanged("tenNXB");
					this.OntenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NXB_tbl_sach", Storage="_tbl_saches", ThisKey="maNXB", OtherKey="maNXB")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NXB = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NXB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sach")]
	public partial class tbl_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSach;
		
		private System.Nullable<int> _maTheLoai;
		
		private System.Nullable<int> _maKho;
		
		private System.Nullable<int> _maNXB;
		
		private string _tenSach;
		
		private string _tenTacGia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<float> _giaTien;
		
		private string _moTa;
		
		private EntitySet<tbl_chi_tiet_muon_tra> _tbl_chi_tiet_muon_tras;
		
		private EntityRef<tbl_kho_sach> _tbl_kho_sach;
		
		private EntityRef<tbl_NXB> _tbl_NXB;
		
		private EntityRef<tbl_the_loai_sach> _tbl_the_loai_sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSachChanging(int value);
    partial void OnmaSachChanged();
    partial void OnmaTheLoaiChanging(System.Nullable<int> value);
    partial void OnmaTheLoaiChanged();
    partial void OnmaKhoChanging(System.Nullable<int> value);
    partial void OnmaKhoChanged();
    partial void OnmaNXBChanging(System.Nullable<int> value);
    partial void OnmaNXBChanged();
    partial void OntenSachChanging(string value);
    partial void OntenSachChanged();
    partial void OntenTacGiaChanging(string value);
    partial void OntenTacGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaTienChanging(System.Nullable<float> value);
    partial void OngiaTienChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    #endregion
		
		public tbl_sach()
		{
			this._tbl_chi_tiet_muon_tras = new EntitySet<tbl_chi_tiet_muon_tra>(new Action<tbl_chi_tiet_muon_tra>(this.attach_tbl_chi_tiet_muon_tras), new Action<tbl_chi_tiet_muon_tra>(this.detach_tbl_chi_tiet_muon_tras));
			this._tbl_kho_sach = default(EntityRef<tbl_kho_sach>);
			this._tbl_NXB = default(EntityRef<tbl_NXB>);
			this._tbl_the_loai_sach = default(EntityRef<tbl_the_loai_sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTheLoai", DbType="Int")]
		public System.Nullable<int> maTheLoai
		{
			get
			{
				return this._maTheLoai;
			}
			set
			{
				if ((this._maTheLoai != value))
				{
					if (this._tbl_the_loai_sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._maTheLoai = value;
					this.SendPropertyChanged("maTheLoai");
					this.OnmaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKho", DbType="Int")]
		public System.Nullable<int> maKho
		{
			get
			{
				return this._maKho;
			}
			set
			{
				if ((this._maKho != value))
				{
					if (this._tbl_kho_sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoChanging(value);
					this.SendPropertyChanging();
					this._maKho = value;
					this.SendPropertyChanged("maKho");
					this.OnmaKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", DbType="Int")]
		public System.Nullable<int> maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					if (this._tbl_NXB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSach", DbType="NVarChar(100)")]
		public string tenSach
		{
			get
			{
				return this._tenSach;
			}
			set
			{
				if ((this._tenSach != value))
				{
					this.OntenSachChanging(value);
					this.SendPropertyChanging();
					this._tenSach = value;
					this.SendPropertyChanged("tenSach");
					this.OntenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTacGia", DbType="NVarChar(50)")]
		public string tenTacGia
		{
			get
			{
				return this._tenTacGia;
			}
			set
			{
				if ((this._tenTacGia != value))
				{
					this.OntenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._tenTacGia = value;
					this.SendPropertyChanged("tenTacGia");
					this.OntenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaTien", DbType="Real")]
		public System.Nullable<float> giaTien
		{
			get
			{
				return this._giaTien;
			}
			set
			{
				if ((this._giaTien != value))
				{
					this.OngiaTienChanging(value);
					this.SendPropertyChanging();
					this._giaTien = value;
					this.SendPropertyChanged("giaTien");
					this.OngiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sach_tbl_chi_tiet_muon_tra", Storage="_tbl_chi_tiet_muon_tras", ThisKey="maSach", OtherKey="maSach")]
		public EntitySet<tbl_chi_tiet_muon_tra> tbl_chi_tiet_muon_tras
		{
			get
			{
				return this._tbl_chi_tiet_muon_tras;
			}
			set
			{
				this._tbl_chi_tiet_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kho_sach_tbl_sach", Storage="_tbl_kho_sach", ThisKey="maKho", OtherKey="maKho", IsForeignKey=true)]
		public tbl_kho_sach tbl_kho_sach
		{
			get
			{
				return this._tbl_kho_sach.Entity;
			}
			set
			{
				tbl_kho_sach previousValue = this._tbl_kho_sach.Entity;
				if (((previousValue != value) 
							|| (this._tbl_kho_sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_kho_sach.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_kho_sach.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._maKho = value.maKho;
					}
					else
					{
						this._maKho = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_kho_sach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NXB_tbl_sach", Storage="_tbl_NXB", ThisKey="maNXB", OtherKey="maNXB", IsForeignKey=true)]
		public tbl_NXB tbl_NXB
		{
			get
			{
				return this._tbl_NXB.Entity;
			}
			set
			{
				tbl_NXB previousValue = this._tbl_NXB.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NXB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NXB.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_NXB.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._maNXB = value.maNXB;
					}
					else
					{
						this._maNXB = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_NXB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_the_loai_sach_tbl_sach", Storage="_tbl_the_loai_sach", ThisKey="maTheLoai", OtherKey="maTheLoai", IsForeignKey=true)]
		public tbl_the_loai_sach tbl_the_loai_sach
		{
			get
			{
				return this._tbl_the_loai_sach.Entity;
			}
			set
			{
				tbl_the_loai_sach previousValue = this._tbl_the_loai_sach.Entity;
				if (((previousValue != value) 
							|| (this._tbl_the_loai_sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_the_loai_sach.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_the_loai_sach.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._maTheLoai = value.maTheLoai;
					}
					else
					{
						this._maTheLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_the_loai_sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sach = this;
		}
		
		private void detach_tbl_chi_tiet_muon_tras(tbl_chi_tiet_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sach = null;
		}
	}
}
#pragma warning restore 1591
